### ISSUE TITLE
Rewrite Svelte components to Vue

### ISSUE THREAD

**Issue by Kobzol** [mrlvsb/kelvin#569]
Eventually, we would like to get rid of Svelte and rewrite web UI components in Vue instead.

- [x] Notifications (https://github.com/mrlvsb/kelvin/pull/556)
- [x] Tasks page (https://github.com/mrlvsb/kelvin/pull/526)
- [x] Color theme chooser (https://github.com/mrlvsb/kelvin/pull/561)
- [x] Task file editor (https://github.com/mrlvsb/kelvin/pull/560)

**Comment by geordi** [comment]
Can be closed now?
